sudo: required

env:
  global:
  - IMAGE=kacis/docker-rpi-ddclient
  - SNAPSHOT=snapshot

services:
- docker

script:
- sh docker-build.sh

after_script:
- docker images;
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker tag "$IMAGE" "$IMAGE:$SNAPSHOT";
- docker images;
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push "$IMAGE:$SNAPSHOT";
  fi

before_deploy:
- git config --global user.email "builds@travis-ci.com";
- git config --global user.name "Travis CI";
- export GIT_TAG=`cat version`;
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER";
- git push -q https://$GITHUB_TOKEN@github.com/$IMAGE --tags;
- docker images;
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker tag "$IMAGE" "$IMAGE:$GIT_TAG";
- docker push "$IMAGE:$GIT_TAG";
- docker push "$IMAGE";
- ls -R;

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: version
  on:
    tags: false
    repo: $IMAGE
    branch: release